// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"database/sql"
)

type Task struct {
	ID        string
	UserID    string
	Content   string
	State     int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID             string
	Email          string
	Name           string
	HashedPassword string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
